### ISSUE TITLE
Gradle config errors on PizzaOrder

### ISSUE THREAD

**Issue by atyshka** [FurhatRobotics/tutorials#5]
When attempting to build the PizzaOrder project in IntelliJ, the gradle sync fails with the following error:

`object is not an instance of declaring class`

There doesn't seem to be any further information indicating what code line is throwing this error. This error does not seem to be present in other skills such as the Fruitseller. I'm using sdk version 2.3.0

**Comment by atyshka** [comment]
I seem to be noticing this on other skills such as WolframAlpha, but the fruit seller skill works fine.

**Comment by atyshka** [comment]
The issue seems to resolve if I change `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-all.zip` in grade-wrapper.properties. Why might this be? Should all the tutorials be updated to 4.5?

**Comment by nilshagberg** [comment]
There seems to be some kind of mixup with what version of gradle intelliJ is expecting. 

The gradle-wrapper.properties is saying 4.1, but IntelliJ is saying 4.5. 

in the IntelliJ preferences - gradle there is an option for: 'User gradle from'. Make sure 'gradle-wrapper.porperties file' is selected and that 'gradle JVM' is pointing to the correct Gradle JVM. It should be 1.8. If you have multiple Java 1.8 JVM's you can test changing between them.

**Comment by atyshka** [comment]
Here is what my gradle options look like:
<img width="718" alt="Screen Shot 2022-05-19 at 11 33 08 AM" src="https://user-images.githubusercontent.com/19317207/169337657-954b2bdb-a6fa-4e0a-9506-cf70f2ccf372.png">
I was using the JVM bundled with the SDK, I also tried the others but I get the same error with all the other options

**Comment by nilshagberg** [comment]
That looks about right. 

When you imported the project to IntelliJ - did you choose 'open' and selecting the directory, or did you select the 
'open project from existing source' and select the build.gradle file? 

I've found that the latter method is a more foolproof way of ensuring IntelliJ and gradle play nice.
