### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Parathps7** [FurhatRobotics/tutorials#8]
How can I use my computer's camera for same while working on sdk?

**Comment by nilshagberg** [comment]
At the moment the SDK does not support using the computers camera. You can create virtual users (by double-clicking in the dashboard) to simulate users when testing an interaction.

**Comment by Parathps7** [comment]
Is there any way I can check camera feed on sdk via my computer's webcam?

**Comment by nilshagberg** [comment]
No. 
The SDK does not make use of a camera stream. The computer vision algorithms for detecting users does not run on the SDK, only on the Robot.
